### ISSUE TITLE
Installation process is broken

### ISSUE THREAD

**Issue by evpxregu** [kbrajwani/resume_parser#4]
Following the set-up does not work since it installs an incompatible version of spacy(3.) with the resume parser.
Can be solved by uninstalling that verison and installing the lower version of spacy 2.3.5.

**Comment by kbrajwani** [comment]
Have you tried this steps https://github.com/kbrajwani/resume_parser/issues/1#issuecomment-830510508 ?

**Comment by evpxregu** [comment]
Thanks, seemed to work! 
Also, I ran into an issue with the program not working properly on some CV's due to not having java installed. (since Tiki is being used which needs java in some cases) 

So running this comment after the installation steps seemed to help with that. 
sudo apt-get install -y openjdk-11-jre-headless
